sudo: false
language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
env:
  - MIX_ENV=test
script:
  - mix compile
  - mix test --trace
notifications:
  email:
    - pikender@vinsol.com
addons:
  postgresql: "9.4"
services:
  - postgresql

before_script:
  - psql -c 'create database ex_shop_test;' -U postgres
